sonar.projectKey=tinuvi_opentelemetry-instrumentation-django-q2-full-of-juice
sonar.organization=tinuvi

sonar.language=py
sonar.python.version=3.14

sonar.sources=opentelemetry_instrumentation_django_q2
sonar.tests=tests
sonar.exclusions=tests/testapp/**,**/migrations/**
sonar.coverage.exclusions=tests/testapp/**,**/migrations/**

sonar.python.coverage.reportPaths=tests-reports/coverage.xml
sonar.python.xunit.reportPath=tests-reports/junit.xml

sonar.verbose=false
