name: Publish coverage report

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'opentelemetry_instrumentation_django_q2/**'
      - 'Dockerfile'
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'sonar-project.properties'
      - '.github/workflows/publish-coverage.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: Execute lint/formatter
        run: docker compose up --build --exit-code-from lint-formatter lint-formatter
      - name: Execute tests
        run: docker compose up --build --exit-code-from integration-tests integration-tests
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
